"""Render one canonical agent into each host's native grant shape."""

from __future__ import annotations

import json
import re
from pathlib import Path

from . import model, resolve

MANIFEST_VERSION = 1


def prefixed(name: str, prefix: str) -> str:
    return name if name.startswith(prefix) else f"{prefix}{name}"


def _rewrite_names(text: str, mapping: dict[str, str]) -> str:
    for source in sorted(mapping, key=len, reverse=True):
        text = re.sub(rf"`{re.escape(source)}`", f"`{mapping[source]}`", text)
    return text


def resolved_instructions(agent: model.Agent, persona: model.Persona,
                          mapping: dict[str, str]) -> str:
    return _rewrite_names(
        resolve.resolve(agent.instructions, persona.id),
        mapping,
    )


def _quoted(value: str) -> str:
    """A JSON string is also a valid TOML basic string and YAML scalar."""
    return json.dumps(value, ensure_ascii=False)


def render_claude(agent: model.Agent, built_name: str, instructions: str) -> str:
    grant = agent.grants["claude"]
    tools = grant["tools"]
    tool_line = ", ".join(tools) if tools else "[]"
    model_line = (
        f"\nmodel: {grant['model']}"
        if grant.get("model")
        else ""
    )
    return (
        "---\n"
        f"name: {built_name}\n"
        f"description: {_quoted(agent.description)}\n"
        f"tools: {tool_line}"
        f"{model_line}\n"
        "---\n\n"
        "<!-- Generated by Skillforge. Edit the canonical agents/*.json source. -->\n\n"
        f"{instructions.strip()}\n"
    )


def render_codex(agent: model.Agent, instructions: str) -> str:
    grant = agent.grants["codex"]
    lines = [
        "# Generated by Skillforge. Edit the canonical agents/*.json source.",
        f"description = {_quoted(agent.description)}",
        f"developer_instructions = {_quoted(instructions.strip())}",
        f"sandbox_mode = {_quoted(grant['sandbox_mode'])}",
        f"web_search = {_quoted(grant['web_search'])}",
    ]
    for key in ("model", "model_reasoning_effort"):
        if grant.get(key):
            lines.append(f"{key} = {_quoted(grant[key])}")
    return "\n".join(lines) + "\n"


def render_kiro(agent: model.Agent, instructions: str) -> dict:
    grant = agent.grants["kiro"]
    return {
        "name": agent.display_name,
        "description": agent.description,
        "prompt": instructions.strip(),
        "tools": grant["tools"],
        "allowedTools": grant["allowed_tools"],
    }


def render_quick(agent: model.Agent, instructions: str) -> dict:
    """The documented fields used by Quick's custom-agent JSON import."""
    return {
        "name": agent.display_name,
        "description": agent.description,
        "instructions": instructions.strip(),
        "tools": agent.grants["quick"]["tools"],
    }


def write_pack_agents(pack: Path, persona: model.Persona, version: str,
                      mapping: dict[str, str], root: Path) -> list[dict]:
    """Write every included agent. Returns the manifest's agent entries."""
    entries: list[dict] = []
    for agent_id in persona.include_agents:
        agent = model.load_agent(agent_id, root)
        built_name = prefixed(agent.id, persona.prefix)
        instructions = resolved_instructions(agent, persona, mapping)

        claude_path = Path("agents") / f"{built_name}.md"
        codex_path = Path("agents") / "codex" / f"{built_name}.toml"
        kiro_path = Path("agents") / "kiro" / f"{built_name}.json"
        quick_path = Path("agents") / "quick" / f"{built_name}.json"
        for path in (claude_path, codex_path, kiro_path, quick_path):
            (pack / path).parent.mkdir(parents=True, exist_ok=True)

        (pack / claude_path).write_text(
            render_claude(agent, built_name, instructions),
            encoding="utf-8",
        )
        (pack / codex_path).write_text(
            render_codex(agent, instructions),
            encoding="utf-8",
        )
        (pack / kiro_path).write_text(
            json.dumps(render_kiro(agent, instructions), indent=2) + "\n",
            encoding="utf-8",
        )
        (pack / quick_path).write_text(
            json.dumps(render_quick(agent, instructions), indent=2) + "\n",
            encoding="utf-8",
        )
        entries.append({
            "source": agent.id,
            "name": built_name,
            "files": {
                "claude": claude_path.as_posix(),
                "codex": codex_path.as_posix(),
                "kiro": kiro_path.as_posix(),
                "quick": quick_path.as_posix(),
            },
            "grants": agent.grants,
        })

    if entries:
        manifest = {
            "schema_version": MANIFEST_VERSION,
            "pack_version": version,
            "persona": persona.id,
            "agents": entries,
        }
        path = pack / "agents" / "manifest.json"
        path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return entries
